version: '3.5'

services:
    php:
        image: webdevops/php-apache:alpine-php7
        ports:
            - "80:80"
        volumes:
            - .:/app
        links:
            - database
    database:
        image: mysql:5.7
        ports:
            - "3306:3036"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=dados_dio
